### ISSUE TITLE
Remove TrajectoriesSampler class

### ISSUE THREAD

**Issue by saleml** [saleml/torchgfn#85]
and make `sample_trajectories`  a method of `Sampler`, which would be the new `ActionsSampler`, requiring only a GFNModule that implements the `to_probability_distribution` method.
After https://github.com/saleml/torchgfn/issues/77 ! Should be close enough to the example provided in the README of #84.

Thoughts @vict0rsch @josephdviviano ?

**Comment by josephdviviano** [comment]
As long as you're willing to stick by that after #77! :) Sounds like a good idea.

**Comment by saleml** [comment]
Done in #95
